import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import {
  useAccount,
  useConnect,
  useDisconnect,
  useEnsAvatar,
  useEnsName,
  useSendTransaction,
  useWaitForTransactionReceipt,
} from 'wagmi';
import { useEffect, useState } from 'react';
import { parseEther } from 'viem';

const inter = Inter({ subsets: ['latin'] });

function WalletOptions() {
  const { connectors, connect } = useConnect();

  return connectors.map((connector) => (
    <button key={connector.uid} onClick={() => connect({ connector })}>
      {connector.name}
    </button>
  ));
}

function Account() {
  const { address } = useAccount();
  const { disconnect } = useDisconnect();
  const { data: ensName } = useEnsName({ address });
  const { data: ensAvatar } = useEnsAvatar({ name: ensName! });

  return (
    <div>
      {ensAvatar && <img alt="ENS Avatar" src={ensAvatar} />}
      {address && <div>{ensName ? `${ensName} (${address})` : address}</div>}
      <button onClick={() => disconnect()}>Disconnect</button>
    </div>
  );
}

function SendEther() {
  const [stage, setStage] = useState('waiting4Tx');
  const { address } = useAccount();
  const { data: hash, sendTransaction } = useSendTransaction({
    mutation: { onSuccess: () => setStage('inProgress') },
  });

  const { data: dataConfirmed, status, isSuccess } = useWaitForTransactionReceipt({ hash });

  useEffect(() => {
    if (dataConfirmed) {
      console.log('dataConfirmed', dataConfirmed);
      setStage('completed');
    }
  }, [dataConfirmed]);

  console.log(`
    hash ${hash}
    status ${status}
    isSuccess ${isSuccess}
  `);

  return address ? (
    <>
      <button onClick={() => sendTransaction({ to: address, value: parseEther('0.01') })}>
        Send 0.01 ETH to {address}
      </button>
      <p>stage: {stage}</p>
      <p>hash {hash}</p>
      <p>
        query, status: {status}, isSuccess: {isSuccess ? 'true' : 'false'}
      </p>
    </>
  ) : (
    'Please connect wallet'
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ display: 'grid', gap: '20px' }}>
          <div style={{ display: 'flex', gap: '12px' }}>
            <WalletOptions />
          </div>
          <div>
            <Account />
          </div>
          <div>
            <SendEther />
          </div>
        </div>
      </main>
    </>
  );
}
